# Generated by Django 2.0.6 on 2018-06-05 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='location',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('spare', 'SPARE'), ('broken', 'BROKEN'), ('recycled', 'RECYCLED'), ('unknown', 'UNKNOWN')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(choices=[('chassis', 'CHASSIS'), ('memory', 'MEMORY'), ('cpu', 'CPU'), ('hdd', 'HDD'), ('ssd', 'SSD'), ('psu', 'PSU'), ('network', 'NETWORK')], max_length=100),
        ),
    ]
