# Generated by Django 2.0.6 on 2018-06-05 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20180605_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='size',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='location',
            field=models.CharField(choices=[('LAB', 'LAB'), ('BRAD', 'BRAD'), ('JOSH', 'JOSH'), ('SEAN', 'SEAN'), ('ASBN', 'ASB        N'), ('SNVA', 'SNVA')], default='lab', max_length=100),
        ),
    ]
