# Generated by Django 2.0.6 on 2018-06-05 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20180605_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='po_number',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
