# Generated by Django 2.0.6 on 2018-06-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20180606_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='delete_date',
        ),
    ]
